### ISSUE TITLE
fix overwriting of __init__.py contents

### ISSUE THREAD

**Issue by JonasScholl** [code-specialist/pypi-poetry-publish#2]
The action updates the version in the `__init__.py`, but overwrites the whole file. Every code in there is just deleted, which should not be the desired behaviour.

**Comment by JonasScholl** [comment]
fixed

**Comment by vk496** [comment]
Just FYI, using `code-specialist/pypi-poetry-publish@v1` still performs with the old behavior.

I had to use explicitly `code-specialist/pypi-poetry-publish@v1.2`
